version: "3.3"

services:
    nginx:
        build:
            context: .
            args:
                - apihost=${REACT_APP_API_HOST}
        container_name: ${PROJECT_NAME}Nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
